### ISSUE TITLE
permission issue when doing a docker pull from gcr

### ISSUE THREAD

**Issue by solackerman** [Shopify/buildkit#11]
### background
Starscream is moving over from locutus to pipa, and in the process, we're seeing around 3min of extra time being added when pushing to legacy registry (PIPA_LEGACY_REPO=registry.shopify.io/starscream-ci). The overarching goal is to minimize as much of that 3min as possible to the ci time. 

### potential solution 1
have the agents pull down their docker containers from gcr. When we do this, however, we hit the following [permission issue](https://buildkite.com/shopify/starscream/builds/62964#915328cd-3564-4d2c-87a2-bc380bc85925)
```
/usr/bin/timeout 5m docker pull gcr.io/shopify-docker-images/apps/ci/starscream:511da35bbc76d04181e37021bfc0dae639c8ef16
Error response from daemon: denied: Permission denied for "511da35bbc76d04181e37021bfc0dae639c8ef16" from request "/v2/shopify-docker-images/apps/ci/starscream/manifests/511da35bbc76d04181e37021bfc0dae639c8ef16".
```

### potential solution 2
Have buildkite run out of GC instead of AWS. I have no idea how to do this.

@DazWorrall

**Comment by DazWorrall** [comment]
Migrated to a separate repo :)
