### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by eredi93** [Shopify/buildkit#14]
correct me if i'm wrong but it seems that the sdk does not support pagination. any chance you could implement that?

**Comment by casperisfine** [comment]
It is supported, the same way than in Octokit. Just follow the `rels[:next]`.

e.g.

```ruby
def each_pipeline
  response = organization.rels[:pipelines].get
  loop do
    response.data.each { |pipeline| yield pipeline }
    return unless response.rels[:next]
    response = response.rels[:next].get
  end
end
```

Unless you meant something else?
